# Generated by Django 5.0.7 on 2024-07-24 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 9, 49, 49, 699883)),
        ),
    ]
